package:
  name: ros-noetic-ros-numpy
  version: 0.0.4
source:
  git_url: https://github.com/eric-wieser/ros_numpy-release.git
  git_rev: release/noetic/ros_numpy/0.0.4-5
  folder: ros-noetic-ros-numpy/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 4
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
    - sel(build_platform != target_platform): pybind11
  host:
    - numpy
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-catkin
    - ros-noetic-geometry-msgs
    - ros-noetic-nav-msgs
    - ros-noetic-rospy
    - ros-noetic-sensor-msgs
    - ros-noetic-tf
  run:
    - numpy
    - python
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-geometry-msgs
    - ros-noetic-nav-msgs
    - ros-noetic-rospy
    - ros-noetic-sensor-msgs
    - ros-noetic-tf
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
