pool:
  vmImage: ubuntu-16.04
trigger:
- buildbranch_linux
pr: none
stages:
- stage: stage_0
  jobs:
  - job: ros_noetic_eigenpy_ros_noetic_ros_numpy
    steps:
    - script: |-
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
      env:
        ANACONDA_API_TOKEN: $(ANACONDA_API_TOKEN)
        CURRENT_RECIPES: ros-noetic-eigenpy ros-noetic-ros-numpy
        DOCKER_IMAGE: condaforge/linux-anvil-comp7
      displayName: Build ros-noetic-eigenpy ros-noetic-ros-numpy
