package:
  name: ros-noetic-geometric-shapes
  version: 0.7.2
source:
  git_url: https://github.com/ros-gbp/geometric_shapes-release.git
  git_rev: release/noetic/geometric_shapes/0.7.2-1
  folder: ros-noetic-geometric-shapes/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 7
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
    - sel(build_platform != target_platform): pybind11
  host:
    - assimp
    - boost
    - console_bridge
    - eigen
    - pkg-config
    - python
    - qhull
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-catkin
    - ros-noetic-eigen-stl-containers
    - ros-noetic-octomap
    - ros-noetic-random-numbers
    - ros-noetic-resource-retriever
    - ros-noetic-rosunit
    - ros-noetic-shape-msgs
    - ros-noetic-visualization-msgs
  run:
    - assimp
    - boost
    - console_bridge
    - eigen
    - python
    - qhull
    - ros-distro-mutex 0.1 noetic
    - ros-noetic-eigen-stl-containers
    - ros-noetic-octomap
    - ros-noetic-random-numbers
    - ros-noetic-resource-retriever
    - ros-noetic-shape-msgs
    - ros-noetic-visualization-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
